import assert from 'node:assert/strict';
import { mkdtemp, rm, readFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { randomUUID } from 'node:crypto';
import { fileURLToPath } from 'node:url';
import { Client } from '@modelcontextprotocol/sdk/client/index.js';
import { StdioClientTransport } from '@modelcontextprotocol/sdk/client/stdio.js';
const dir=await mkdtemp(join(tmpdir(),'spellout-experience-'));
async function connect(){const c=new Client({name:'experience-test',version:'1'});await c.connect(new StdioClientTransport({command:process.execPath,args:[fileURLToPath(new URL('../server/index.mjs',import.meta.url))],env:{...process.env,SPELLOUT_ANSWERS_DIR:dir,SPELLOUT_SETTINGS_PATH:join(dir,'preferences.json')}}));return c;}
let client=await connect();const other=await connect();
const call=(name,args,c=client)=>c.callTool({name:'spellout_'+name,arguments:args});
const unwrap=async promise=>{const r=await promise;assert.ok(!r.isError,JSON.stringify(r));return r.structuredContent;};
const question={question:'如何改善？',reason:'决定下一步的工作范围',options:[{label:'三项一起'},{label:'先做一项'}]};
try{
 const card=await unwrap(call('ask',{...question,brief:{goal:'减少重复解释',confirmed:'三项一起做',open:'最终视觉待验证'}}));
 const id=card.decisionId,ctx=card.context;
 assert.equal(card.questions[0].reason,question.reason);
 const defaults=await unwrap(call('preferences',{}));
 const prefs={intensity:'deep',coverage:'broad',depth:'motivation',frequency:'discovery',diversity:'exploratory',challenge:'challenge',questionsPerRound:2};
 const update={action:'update',contextId:ctx.contextId,expectedVersion:0,requestId:randomUUID(),preferences:prefs};
 const updated=await unwrap(call('context',update));
 assert.equal(updated.version,1);assert.equal(updated.policy.questionsPerRound,2);
 assert.equal((await unwrap(call('context',update))).version,1,'retry is idempotent');
 assert.deepEqual((await unwrap(call('preferences',{}))).preferences,defaults.preferences,'task change leaves defaults alone');
 assert.equal((await call('context',{...update,requestId:randomUUID(),brief:{goal:'stale'}})).isError,true,'stale edit cannot overwrite');
 const next=await unwrap(call('ask',{...question,contextId:ctx.contextId}));
 assert.deepEqual(next.context.preferences,prefs,'next card reuses task settings');
 assert.equal((await call('ask',{questions:[question,question,question],contextId:ctx.contextId})).isError,true,'task question count is enforced');
 const isolated=await unwrap(call('ask',question));
 assert.notEqual(isolated.contextId,ctx.contextId);assert.deepEqual(isolated.context.preferences,defaults.preferences);
 const reader=await unwrap(call('read_answer',{decisionId:id}));
 assert.equal(reader.context.version,1,'model reads current settings through pending card');
 assert.match(reader.context.policy.instructions.join('\n'),/counterexamples/);
 const briefUpdate={action:'update',contextId:ctx.contextId,expectedVersion:1,requestId:randomUUID(),brief:{goal:'新的目标',confirmed:'明确的要求',open:'仍未知'}};
 const racing=await Promise.all([call('context',briefUpdate),call('context',{...briefUpdate,requestId:randomUUID(),brief:{goal:'另一窗口'}},other)]);
 assert.equal(racing.filter(r=>!r.isError).length,1,'one context writer wins across processes');
 await unwrap(call('submit_answer',{decisionId:id,answers:[{picks:[0]}]}));
 await unwrap(call('acknowledge',{decisionId:id,revision:0,nextStep:'开始检查三项之间的衔接'}));
 const acknowledged=await unwrap(call('read_answer',{decisionId:id}));
 assert.equal(acknowledged.acknowledgement.revision,0);assert.equal(acknowledged.processed,true,'MCP read exposes persistent processed marker');
 const correction={decisionId:id,expectedRevision:0,requestId:randomUUID(),answers:[{picks:[1]}]};
 assert.equal((await unwrap(call('revise_answer',correction))).revision,1);
 assert.equal((await unwrap(call('revise_answer',correction))).revision,1,'correction retry does not create another revision');
 let latest=await unwrap(call('read_answer',{decisionId:id}));
 assert.deepEqual(latest.items[0].answers,['先做一项']);assert.equal(latest.acknowledgement,undefined,'old acknowledgement cannot confirm new answer');assert.equal(latest.processed,false,'new correction must be processed independently');
 assert.equal((await call('acknowledge',{decisionId:id,revision:0,nextStep:'stale'})).isError,true);
 assert.equal((await call('revise_answer',{...correction,requestId:randomUUID(),answers:[{picks:[0]}]})).isError,true);
 assert.deepEqual(JSON.parse(await readFile(join(dir,`${id}.answer.json`),'utf8')).items[0].answers,['三项一起'],'original answer preserved');
 const writes=await Promise.all([call('revise_answer',{...correction,expectedRevision:1,requestId:randomUUID(),answers:[{picks:[0]}]}),call('revise_answer',{...correction,expectedRevision:1,requestId:randomUUID(),answers:[{picks:[2],custom:'另一个想法'}]},other)]);
 assert.equal(writes.filter(r=>!r.isError).length,1,'one correction writer wins');
 const current=await unwrap(call('read_answer',{decisionId:id}));assert.equal(current.revision,2);
 assert.equal((await call('revise_answer',{...correction,decisionId:isolated.decisionId})).isError,true,'cannot revise a pending card');
 await client.close();client=await connect();
 assert.equal((await unwrap(call('read_answer',{decisionId:id}))).revision,2);
 assert.equal((await unwrap(call('context',{contextId:ctx.contextId}))).version,2,'context persists across restart');
 assert.equal((await unwrap(call('preferences',{action:'set',preferences:prefs}))).policy.questionsPerRound,2,'explicit default save supported');
 console.log('Experience passed: task scope, summary conflicts, correction history, retries, acknowledgements, concurrency and restart');
}finally{await client.close();await other.close();await rm(dir,{recursive:true,force:true});}
