import assert from 'node:assert/strict';
import { mkdtemp, rm, writeFile, access } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { Client } from '@modelcontextprotocol/sdk/client/index.js';
import { StdioClientTransport } from '@modelcontextprotocol/sdk/client/stdio.js';
import { fileURLToPath } from 'node:url';
const folder = await mkdtemp(join(tmpdir(), 'spellout-preferences-'));
const file = join(folder, 'settings.json');
async function connect() {
  const client = new Client({ name: 'preferences-test', version: '1' });
  await client.connect(new StdioClientTransport({ command: process.execPath, args: [fileURLToPath(new URL('../server/index.mjs', import.meta.url))], env: { ...process.env, SPELLOUT_SETTINGS_PATH: file, SPELLOUT_ANSWERS_DIR: join(folder, 'answers'), SPELLOUT_UI_RESOURCES_DIR: join(folder, 'ui-resources') } }));
  return client;
}
let client = await connect();
const call = args => client.callTool({ name: 'spellout_preferences', arguments: args });
try {
  const first = (await call({})).structuredContent;
  assert.equal(first.onboarding?.required, true, 'first use offers preference onboarding');
  assert.equal(first.policy.intensity, 'deep', 'new users get proactive exploration');
  assert.equal(first.policy.coverage, 'broad');
  assert.equal(first.policy.depth, 'motivation');
  assert.equal(first.policy.frequency, 'discovery');
  assert.deepEqual(first.onboarding.presets.map(p => p.preferences.intensity), ['deep', 'balanced', 'minimal']);
  assert.equal((await call({ preferences: { intensity: 'minimal' } })).structuredContent.onboarding.required, true, 'task override does not complete onboarding');
  assert.equal((await call({})).structuredContent.onboarding.required, true, 'reading alone never completes onboarding');
  await assert.rejects(access(file), { code: 'ENOENT' }, 'read and task override do not persist inferred settings');
  const setupQuestion = { question: first.onboarding.question, options: first.onboarding.presets.map(({ label, description }) => ({ label, description })) };
  const card = await client.callTool({ name: 'spellout_ask', arguments: setupQuestion });
  assert.equal(card.isError, undefined);
  const decisionId = card.structuredContent.decisionId;
  const submitted = await client.callTool({ name: 'spellout_submit_answer', arguments: { decisionId, answers: [{ picks: [2] }] } });
  assert.equal(submitted.isError, undefined);
  const answer = await client.callTool({ name: 'spellout_read_answer', arguments: { decisionId } });
  assert.equal(answer.structuredContent.items[0].answers[0], first.onboarding.presets[2].label);
  assert.equal((await call({})).structuredContent.onboarding.required, true, 'card submission alone does not implicitly save global preferences');
  const chosen = first.onboarding.presets.find(p => p.label === answer.structuredContent.items[0].answers[0]).preferences;
  assert.equal((await call({ action: 'set', preferences: chosen })).structuredContent.onboarding.required, false);
  await client.close(); client = await connect();
  const returning = (await call({})).structuredContent;
  assert.equal(returning.onboarding.required, false, 'no repeated onboarding after restart');
  assert.equal(returning.policy.frequency, 'blocking', 'explicit minimal choice overrides proactive defaults');
  const task = await client.callTool({ name: 'spellout_ask', arguments: { ...setupQuestion, question: '这项阻塞决定选哪个？' } });
  assert.equal(task.structuredContent.context.policy.intensity, 'minimal', 'new task card uses chosen policy, not onboarding policy');
  assert.notEqual(task.structuredContent.contextId, card.structuredContent.contextId);
  await client.callTool({ name: 'spellout_dismiss', arguments: { decisionId: task.structuredContent.decisionId } });
  await writeFile(file, JSON.stringify({ intensity: 'balanced', coverage: 'broad' }));
  const existing = (await call({})).structuredContent;
  assert.equal(existing.onboarding.required, false, 'existing saved preferences need no onboarding');
  assert.equal(existing.policy.intensity, 'balanced', 'existing users keep their preferences');
  assert.equal(existing.policy.coverage, 'broad');
  assert.equal((await call({ action: 'set', preferences: { intensity: 'deep' } })).structuredContent.policy.depth, 'motivation');
  await client.close(); client = await connect();
  assert.equal((await call({})).structuredContent.policy.intensity, 'deep', 'saved preference survives server restart');
  const temporary = await call({ preferences: { intensity: 'minimal' } });
  assert.equal(temporary.structuredContent.scope, 'task');
  assert.equal(temporary.structuredContent.policy.questionsPerRound, 1);
  assert.equal((await call({})).structuredContent.policy.intensity, 'deep', 'task override does not overwrite default');
  assert.equal((await call({ preferences: { intensity: 'deep', frequency: 'milestones' } })).structuredContent.policy.frequency, 'milestones');
  assert.equal((await call({ action: 'set' })).isError, true);
  const five = await call({ action: 'set', preferences: { intensity: 'deep', questionsPerRound: 5 } });
  assert.equal(five.isError, undefined, 'users can choose five questions per round');
  assert.equal(five.structuredContent.policy.questionsPerRound, 5);
  const fiveCard = await client.callTool({ name: 'spellout_ask', arguments: { questions: Array.from({length:5},(_,i)=>({...setupQuestion,question:'Question '+i})) } });
  assert.equal(fiveCard.isError, undefined, 'five independent questions are accepted');
  const sixCard = await client.callTool({ name: 'spellout_ask', arguments: { questions: Array(6).fill(setupQuestion) } });
  assert.equal(sixCard.isError, true, 'six questions remain unsupported');
  assert.equal((await call({ action:'update', preferences:{questionsPerRound:6} })).isError, true);
  await client.close(); client = await connect();
  assert.equal((await call({})).structuredContent.policy.questionsPerRound, 5, 'five-question preference survives restart');
  await call({ action: 'set', preferences: { intensity: 'deep', coverage: 'broad', questionsPerRound: 2 } });
  const adjusted = await call({ action: 'update', preferences: { frequency: 'milestones' } });
  assert.equal(adjusted.isError, undefined, 'single-control updates are supported');
  assert.equal(adjusted.structuredContent.policy.intensity, 'deep', 'changing frequency retains the preset');
  assert.equal(adjusted.structuredContent.policy.coverage, 'broad');
  assert.equal(adjusted.structuredContent.policy.questionsPerRound, 2, 'changing frequency retains round size');
  assert.equal(adjusted.structuredContent.policy.frequency, 'milestones');
  assert.equal((await call({ action: 'update', preferences: {} })).isError, true, 'empty update is not a preference choice');
  assert.equal((await call({ action: 'update' })).isError, true);
  await client.close(); client = await connect();
  assert.deepEqual((await call({})).structuredContent.preferences, adjusted.structuredContent.preferences, 'partial update persists');
  await writeFile(file, 'broken');
  assert.equal((await call({})).isError, true, 'corrupt settings are not silently overwritten');
  assert.equal((await call({ action: 'update', preferences: { questionsPerRound: 1 } })).isError, true, 'partial update cannot overwrite unreadable settings');
  const reset = (await call({ action: 'reset' })).structuredContent;
  assert.equal(reset.policy.intensity, 'deep');
  assert.equal(reset.onboarding.required, false, 'explicit reset is itself a preference choice');
  console.log('Preferences passed: first-use preset card, explicit saving, new task policy, persistence, override, validation, recovery');
} finally { await client.close(); await rm(folder, { recursive: true, force: true }); }
